name: TestDriver.ai

permissions:
  actions: read
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  test:
    name: "TestDriver"
    runs-on: ubuntu-latest
    steps:
      - uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: |
            1. /run testdriver/test.yml
          prerun: |
            # Define variables
            $osInstallerUrl = "https://builds.pieces.app/stages/production/os_server/windows-exe/download"
            $appInstallerUrl = "https://builds.pieces.app/stages/production/pieces_for_x/windows-exe/download"
            $osInstallerPath = "$env:USERPROFILE\Downloads\out-windows.exe"
            $appInstallerPath = "$env:USERPROFILE\Downloads\out-windows (1).exe"

            function Install-Application($installerUrl, $installerPath, $appName) {
              Write-Host "$(Get-Date -Format G): Starting download of $appName installer..."

              # Create WebClient object
              $webClient = New-Object System.Net.WebClient

              # Event handler for download progress
              $webClient.DownloadProgressChanged += {
                $percent = $_.ProgressPercentage
                Write-Host "$(Get-Date -Format G): Downloading $appName - $percent% complete"
              }

              # Download file asynchronously
              $webClient.DownloadFileAsync($installerUrl, $installerPath)

              while ($webClient.IsBusy) {
                Start-Sleep -Milliseconds 500
              }

              Write-Host "$(Get-Date -Format G): $appName installer download complete."

              if (Test-Path $installerPath) {
                Write-Host "$(Get-Date -Format G): Running the $appName installer..."
                Start-Process -FilePath $installerPath -ArgumentList '/S' -Wait
                Start-Sleep -Seconds 10
              } else {
                Write-Host "$(Get-Date -Format G): Failed to download the $appName installer."
              }
            }

            Install-Application $osInstallerUrl $osInstallerPath "Pieces OS Server"
            Install-Application $appInstallerUrl $appInstallerPath "Pieces Application"

            Write-Host "$(Get-Date -Format G): Attempting to start the Pieces application..."
            $piecesExePath = "C:\Program Files\Pieces for Developers\pieces_for_x.exe"

            if (Test-Path $piecesExePath) {
              Start-Process -FilePath $piecesExePath
              Write-Host "$(Get-Date -Format G): Pieces application started successfully."
            } else {
              Write-Host "$(Get-Date -Format G): Failed to find the Pieces application executable."
            }
        env:
          FORCE_COLOR: "3"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}